apiVersion: batch/v1
kind: CronJob
metadata:
  name: datadis-gather-starter
  namespace: sime-prod-ingestors
spec:
  suspend: false
  schedule: "0 22 */2 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            logger: datadis-logger
          annotations:
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        spec:
          hostAliases:
          - ip: "10.0.88.76"
            hostnames:
            - "master1.internal"
          - ip: "10.0.87.95"
            hostnames:
              - "master2.internal"
          - ip: "10.0.88.132"
            hostnames:
              - "worker1.internal"
          - ip: "10.0.86.33"
            hostnames:
              - "worker2.internal"
          - ip: "10.0.87.145"
            hostnames:
              - "worker3.internal"
          - ip: "10.0.86.214"
            hostnames:
              - "worker4.internal"
          - ip: "10.0.129.220"
            hostnames:
              - "kafka1.internal"
          - ip: "10.0.88.175"
            hostnames:
              - "database1-vpn"
          - ip: "10.0.88.151"
            hostnames:
              - "database2-vpn"
          - ip: "10.0.87.50"
            hostnames:
              - "database3-vpn"
          containers:
          - name: datadis-gather-starter
            image: 853583158095.dkr.ecr.eu-west-1.amazonaws.com/ecr-beegroup-datadis-ingestor:prod
            command: ["python3", "launcher.py", "-l", "producer", "-n", "10"]
            env:
              - name: CONF_FILE
                value: "config.json"
            volumeMounts:
            - name: datadis-base-secret
              mountPath: /datadis/config.json
              subPath: config.json
            - name: datadis-plugins-secret
              mountPath: /datadis/plugins/secrets/
            - name: kafka-secret
              mountPath: /datadis/ca.crt
              subPath: ca.crt
            - name: kafka-user-secret
              mountPath: /datadis/user.crt
              subPath: user.crt
            - name: kafka-user-secret
              mountPath: /datadis/user.key
              subPath: user.key
          volumes:
          - name: datadis-base-secret
            secret:
              secretName: datadis-base-secret
              items:
              - key: config.json
                path: config.json
          - name: datadis-plugins-secret
            secret:
              secretName: datadis-plugins-secret
          - name: kafka-secret
            secret:
              secretName: strimzi-cluster-cluster-ca-cert
              items:
                - key: ca.crt
                  path: ca.crt
          - name: kafka-user-secret
            secret:
              secretName: admin-user
              items:
                - key: user.crt
                  path: user.crt
                - key: user.key
                  path: user.key
          restartPolicy: Never
          imagePullSecrets:
          - name: odin1pullsecret
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: datadis-gather-consumer
  namespace: sime-prod-ingestors
spec:
  suspend: false
  schedule: "10 22 */2 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 10
      parallelism: 10
      completionMode: Indexed
      template:
        metadata:
          labels:
            logger: datadis-logger
          annotations:
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        spec:
          hostAliases:
          - ip: "10.0.88.76"
            hostnames:
            - "master1.internal"
          - ip: "10.0.87.95"
            hostnames:
              - "master2.internal"
          - ip: "10.0.88.132"
            hostnames:
              - "worker1.internal"
          - ip: "10.0.86.33"
            hostnames:
              - "worker2.internal"
          - ip: "10.0.87.145"
            hostnames:
              - "worker3.internal"
          - ip: "10.0.86.214"
            hostnames:
              - "worker4.internal"
          - ip: "10.0.129.220"
            hostnames:
              - "kafka1.internal"
          - ip: "10.0.88.175"
            hostnames:
              - "database1-vpn"
          - ip: "10.0.88.151"
            hostnames:
              - "database2-vpn"
          - ip: "10.0.87.50"
            hostnames:
              - "database3-vpn"
          containers:
          - name: datadis-gather-consumer
            image: 853583158095.dkr.ecr.eu-west-1.amazonaws.com/ecr-beegroup-datadis-ingestor:prod
            command: ["python3", "launcher.py", "-l", "consumer", "-n", "10"]
            env:
              - name: CONF_FILE
                value: "config.json"
            volumeMounts:
            - name: datadis-base-secret
              mountPath: /datadis/config.json
              subPath: config.json
            - name: datadis-plugins-secret
              mountPath: /datadis/plugins/secrets/
            - name: kafka-secret
              mountPath: /datadis/ca.crt
              subPath: ca.crt
            - name: kafka-user-secret
              mountPath: /datadis/user.crt
              subPath: user.crt
            - name: kafka-user-secret
              mountPath: /datadis/user.key
              subPath: user.key
          volumes:
          - name: datadis-base-secret
            secret:
              secretName: datadis-base-secret
              items:
              - key: config.json
                path: config.json
          - name: datadis-plugins-secret
            secret:
              secretName: datadis-plugins-secret
          - name: kafka-secret
            secret:
              secretName: strimzi-cluster-cluster-ca-cert
              items:
                - key: ca.crt
                  path: ca.crt
          - name: kafka-user-secret
            secret:
              secretName: admin-user
              items:
                - key: user.crt
                  path: user.crt
                - key: user.key
                  path: user.key
          restartPolicy: Never
          imagePullSecrets:
          - name: odin1pullsecret

 #kubectl create secret generic datadis-base-secret --from-file=config.json=config.json -n datadis
 #kubectl create secret generic datadis-base-secret --from-file=config.json=config2.json -n sime-prod-ingestors

 #kubectl create secret generic datadis-plugins-secret --from-file=config_plugin_x.json=config_plugin_x.json --from-file=config_plugin_y.json=config_plugin_y.json -n datadis
